### ISSUE TITLE
Offline handling

### ISSUE THREAD

**Issue by gr01d** [alphasp/pxview#47]
After some time of not using the app, I got automatically logged out. Is there any plan to add a 'remember me' functionality for the username and password?

**Comment by alphasp** [comment]
> After some time of not using the app, I got automatically logged out. Is there any plan to add a 'remember me' functionality for the username and password?

How long since your last open the app?  The app do remember login, some possible reasons that could caused auto logged out:
- Your authentication refresh token get invalidated by pixiv 
- Your account was banned by pixiv
- Your device internet connection is not stable or offline while opening the app (will receive network error message on login page)

**Comment by gr01d** [comment]
I have unstable internet connection, it could be that. The error message disappears before I can read it.

**Comment by alphasp** [comment]
> I have unstable internet connection, it could be that. The error message disappears before I can read it.

Will add offline handling to todo list

**Comment by gr01d** [comment]
Thanks.
So, to avoid the issue. I just need to make sure that the app receives internet connection everytime I run it? I use a firewall to block internet from apps that I don't use for some time and unblock them when I use them.

**Comment by gr01d** [comment]
This still happens in the latest version/
