### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by xraidenra** [alphasp/pxview#74]
I've tried it with 2 account and it's always ended up with "invalid grant_type parameter or parameter missing" note, anyone know how to fix this?

**Comment by alphasp** [comment]
Pixiv side changed their login flow which break old login flow. This was fixed in version 4.7, however it is not available on Google Play as Google suspended my app after reviewed my update. 
I am working on publishing new version under new app name, in the mean time you can download apk version 4.7 from https://github.com/alphasp/pxview/releases/tag/v4.7.0 and install it directly.

**Comment by alphasp** [comment]
PxView is now available on Google Play under new name PxView R, https://play.google.com/store/apps/details?id=com.utopia.pxviewr , please download and install from Google Play.

**Comment by paul12sava** [comment]
What happend to the old log in screen, now it's just the normal pixiv log in screen? Also my  account which i registered within the pxview app doesn't work anymore.

**Comment by alphasp** [comment]
> What happend to the old log in screen, now it's just the normal pixiv log in screen? Also my account which i registered within the pxview app doesn't work anymore.

Pixiv side make changes on authentication flow, you are now require to login through pixiv site.
If you never register your old account with email, please register a new pixiv account and login with the new account.
